<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [peopleandtech]" duration-ms="8299" started-at="2019-11-18T03:36:42Z" finished-at="2019-11-18T03:36:50Z">
    <groups>
    </groups>
    <test name="PintTech Test(failed)" duration-ms="8299" started-at="2019-11-18T03:36:42Z" finished-at="2019-11-18T03:36:50Z">
      <class name="com.pint.TestCases.TC_LogainTest_001">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.pint.TestCases.TC_LogainTest_001@239963d8]" name="setUp" is-config="true" duration-ms="6269" started-at="2019-11-18T03:36:42Z" finished-at="2019-11-18T03:36:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="logainTest()[pri:0, instance:com.pint.TestCases.TC_LogainTest_001@239963d8]" name="logainTest" duration-ms="1361" started-at="2019-11-18T03:36:48Z" finished-at="2019-11-18T03:36:50Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.pint.TestCases.TC_LogainTest_001.logainTest(TC_LogainTest_001.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logainTest -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.pint.TestCases.TC_LogainTest_001@239963d8]" name="close" is-config="true" duration-ms="651" started-at="2019-11-18T03:36:50Z" finished-at="2019-11-18T03:36:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.pint.TestCases.TC_LogainTest_001 -->
    </test> <!-- PintTech Test(failed) -->
  </suite> <!-- Failed suite [peopleandtech] -->
</testng-results>
